In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
corpus=pd.read_csv('/content/drive/MyDrive/Data Science/Datasets/all_rev.tsv', sep= '\t')

In [ ]:
corpus.shape

(10000, 2)

In [ ]:
corpus.iloc[9]['review']

'Whispers of the Wicked Saints: This was a easy to read book that made me want to keep reading on and on, not easy to put down.It left me wanting to read the follow on, which I hope is coming soon. I used to read a lot but have gotten away from it. This book made me want to read again. Very enjoyable.'

In [ ]:
corpus

     label                                             review
0      pos  Stuning even for the non-gamer: This sound tra...
1      pos  The best soundtrack ever to anything.: I'm rea...
2      pos  Amazing!: This soundtrack is my favorite music...
3      pos  Excellent Soundtrack: I truly like this soundt...
4      pos  Remember, Pull Your Jaw Off The Floor After He...
...    ...                                                ...
9995   pos  A revelation of life in small town America in ...
9996   pos  Great biography of a very interesting journali...
9997   neg  Interesting Subject; Poor Presentation: You'd ...
9998   neg  Don't buy: The box looked used and it is obvio...
9999   pos  Beautiful Pen and Fast Delivery.: The pen was ...

[10000 rows x 2 columns]

In [ ]:
pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.2.25)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 2.6 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [ ]:
se = SentimentIntensityAnalyzer()

In [ ]:
corpus.iloc[1]['review']

"The best soundtrack ever to anything.: I'm reading a lot of reviews saying that this is the best 'game soundtrack' and I figured that I'd write a review to disagree a bit. This in my opinino is Yasunori Mitsuda's ultimate masterpiece. The music is timeless and I'm been listening to it for years now and its beauty simply refuses to fade.The price tag on this is pretty staggering I must say, but if you are going to buy any cd for this much money, this is the only one that I feel would be worth every penny."

In [ ]:
se.polarity_scores(corpus.iloc[1]['review'])

{'neg': 0.017, 'neu': 0.846, 'pos': 0.137, 'compound': 0.8957}

In [ ]:
s='the movie was the worst movies i have ever seen'

In [ ]:
se.polarity_scores(s)

{'neg': 0.313, 'neu': 0.687, 'pos': 0.0, 'compound': -0.6249}

In [ ]:
s='the movie was the best movies i have ever seen'

In [ ]:
se.polarity_scores(s)

{'neg': 0.0, 'neu': 0.682, 'pos': 0.318, 'compound': 0.6369}

In [ ]:
mult=lambda x,y,z:x*y*z

In [ ]:
mult(5,2,7)

70

In [ ]:
corpus['polarity_scores']=corpus['review'].apply(lambda x: se.polarity_scores(x))

In [ ]:
corpus

,label,review,polarity_scores
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.085, 'neu': 0.682, 'pos': 0.233, 'co..."
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.017, 'neu': 0.846, 'pos': 0.137, 'co..."
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.062, 'neu': 0.674, 'pos': 0.264, 'co..."
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.086, 'neu': 0.632, 'pos': 0.282, 'co..."
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.72, 'pos': 0.28, 'compou..."
...,...,...,...
9995,pos,A revelation of life in small town America in ...,"{'neg': 0.017, 'neu': 0.852, 'pos': 0.132, 'co..."
9996,pos,Great biography of a very interesting journali...,"{'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'comp..."
9997,neg,Interesting Subject; Poor Presentation: You'd ...,"{'neg': 0.062, 'neu': 0.763, 'pos': 0.175, 'co..."
9998,neg,Don't buy: The box looked used and it is obvio...,"{'neg': 0.087, 'neu': 0.913, 'pos': 0.0, 'comp..."
9999,pos,Beautiful Pen and Fast Delivery.: The pen was ...,"{'neg': 0.027, 'neu': 0.821, 'pos': 0.152, 'co..."

In [ ]:
corpus['compound']= corpus ['polarity_scores'].apply(lambda x: x['compound'])

In [ ]:
corpus

,label,review,polarity_scores,compound
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.085, 'neu': 0.682, 'pos': 0.233, 'co...",0.9454
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.017, 'neu': 0.846, 'pos': 0.137, 'co...",0.8957
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.062, 'neu': 0.674, 'pos': 0.264, 'co...",0.9847
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.086, 'neu': 0.632, 'pos': 0.282, 'co...",0.9814
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.72, 'pos': 0.28, 'compou...",0.9840
...,...,...,...,...
9995,pos,A revelation of life in small town America in ...,"{'neg': 0.017, 'neu': 0.852, 'pos': 0.132, 'co...",0.9610
9996,pos,Great biography of a very interesting journali...,"{'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'comp...",0.9544
9997,neg,Interesting Subject; Poor Presentation: You'd ...,"{'neg': 0.062, 'neu': 0.763, 'pos': 0.175, 'co...",0.9467
9998,neg,Don't buy: The box looked used and it is obvio...,"{'neg': 0.087, 'neu': 0.913, 'pos': 0.0, 'comp...",-0.3595
9999,pos,Beautiful Pen and Fast Delivery.: The pen was ...,"{'neg': 0.027, 'neu': 0.821, 'pos': 0.152, 'co...",0.9107

In [ ]:
age=4

In [ ]:
print('you are eligible to vote') if(age>=18) else print('you are not eligible')

you are not eligible

In [ ]:
corpus['sentiment']=corpus['compound'].apply(lambda x: 'pos' if x>=0 else 'neg')

In [ ]:
corpus

,label,review,polarity_scores,compound,sentiment
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.085, 'neu': 0.682, 'pos': 0.233, 'co...",0.9454,pos
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.017, 'neu': 0.846, 'pos': 0.137, 'co...",0.8957,pos
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.062, 'neu': 0.674, 'pos': 0.264, 'co...",0.9847,pos
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.086, 'neu': 0.632, 'pos': 0.282, 'co...",0.9814,pos
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.72, 'pos': 0.28, 'compou...",0.9840,pos
...,...,...,...,...,...
9995,pos,A revelation of life in small town America in ...,"{'neg': 0.017, 'neu': 0.852, 'pos': 0.132, 'co...",0.9610,pos
9996,pos,Great biography of a very interesting journali...,"{'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'comp...",0.9544,pos
9997,neg,Interesting Subject; Poor Presentation: You'd ...,"{'neg': 0.062, 'neu': 0.763, 'pos': 0.175, 'co...",0.9467,pos
9998,neg,Don't buy: The box looked used and it is obvio...,"{'neg': 0.087, 'neu': 0.913, 'pos': 0.0, 'comp...",-0.3595,neg
9999,pos,Beautiful Pen and Fast Delivery.: The pen was ...,"{'neg': 0.027, 'neu': 0.821, 'pos': 0.152, 'co...",0.9107,pos

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
y_true=corpus['label']
y_pred=corpus['sentiment']

In [ ]:
confusion_matrix(y_true, y_pred)

array([[2630, 2467],
       [ 403, 4500]])

In [ ]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

         neg       0.87      0.52      0.65      5097
         pos       0.65      0.92      0.76      4903

    accuracy                           0.71     10000
   macro avg       0.76      0.72      0.70     10000
weighted avg       0.76      0.71      0.70     10000